os:
  - osx
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode11
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
env:
  - global:
    - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2019-08-01-a
    - CODECOV_TOKEN=7eef894d-9ca9-4cac-9356-04dd8ab8a73b
  - matrix:
    - SWIFT_VERSION=5.0
    - SWIFT_VERSION=5.0.1
    - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-08-14-a
script:
  - swift package update
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then
      swift package generate-xcodeproj;
      xcodebuild -quiet -project Structure.xcodeproj -scheme Structure-Package -enableCodeCoverage YES build test;
      bash <(curl -s https://codecov.io/bash);
    else
      swift test -c release;
    fi
after_success: 
  - git clone https://github.com/dn-m/Documentarian && cd Documentarian
  - swift build -c release -Xswiftc -static-stdlib
  - cd ../
  - Documentarian/.build/Release/Documentarian
